<a href="https://colab.research.google.com/github/muhammad-usman-tech/data-analysis-tasks/blob/main/data_aggregation_revise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
df=pd.read_csv('website_wata.csv')
df.shape
df.columns
df.head()
df['Page_name']=np.random.choice(['face book','youtube','instagram',"tiktok",'snapchat'],size=len(df))

df.groupby('Page_name')['Time on Page'].sum().sort_values(ascending=False)
df.groupby('Page_name')['Page Views'].sum().sort_values(ascending=False).head(1)

# for finding the unique user's in this way because i dont have any data on wich i can count all these on the daily basis
a=df_selected=df[df['Previous Visits']==0]
df_selected.head()
print('===')
print(len(a))

In [ ]:
import pandas as pd
import numpy as np
df=pd.read_csv('Sample - Superstore.csv',encoding='latin1')
df.shape
print(df.head())
df.dtypes
# there was no single column that shoes the price per product so temporarily i used the sales but it is the total sales and already
# counted
df['Total_Sales']=df['Quantity']*df['Sales']
df['Total_Sales']

df.groupby('Region')['Sales'].sum().sort_values(ascending=False)
df['Product Name'] # seems like ok so not exploiding it
df.groupby('Product Name')['Quantity'].mean().sort_values(ascending=False).head(3)
# creating the summary by the month using the order date
df['Order Date']=pd.to_datetime(df['Order Date'],format='mixed')

df['Months']=df['Order Date'].dt.month_name()
df['Months']

df.groupby('Months')['Sales'].sum().sort_values(ascending=False) #nov,sep,dec got the top 3

df.groupby('Product Name')['Sales'].sum().sort_values(ascending=False).head(3)

   Row ID        Order ID  Order Date   Ship Date       Ship Mode Customer ID  \
0       1  CA-2016-152156   11/8/2016  11/11/2016    Second Class    CG-12520
1       2  CA-2016-152156   11/8/2016  11/11/2016    Second Class    CG-12520
2       3  CA-2016-138688   6/12/2016   6/16/2016    Second Class    DV-13045
3       4  US-2015-108966  10/11/2015  10/18/2015  Standard Class    SO-20335
4       5  US-2015-108966  10/11/2015  10/18/2015  Standard Class    SO-20335

     Customer Name    Segment        Country             City  ...  \
0      Claire Gute   Consumer  United States        Henderson  ...
1      Claire Gute   Consumer  United States        Henderson  ...
2  Darrin Van Huff  Corporate  United States      Los Angeles  ...
3   Sean O'Donnell   Consumer  United States  Fort Lauderdale  ...
4   Sean O'Donnell   Consumer  United States  Fort Lauderdale  ...

  Postal Code  Region       Product ID         Category Sub-Category  \
0       42420   South  FUR-BO-10001798        Furniture    Bookcases
1       42420   South  FUR-CH-10000454        Furniture       Chairs
2       90036    West  OFF-LA-10000240  Office Supplies       Labels
3       33311   South  FUR-TA-10000577        Furniture       Tables
4       33311   South  OFF-ST-10000760  Office Supplies      Storage

                                        Product Name     Sales  Quantity  \
0                  Bush Somerset Collection Bookcase  261.9600         2
1  Hon Deluxe Fabric Upholstered Stacking Chairs,...  731.9400         3
2  Self-Adhesive Address Labels for Typewriters b...   14.6200         2
3      Bretford CR4500 Series Slim Rectangular Table  957.5775         5
4                     Eldon Fold 'N Roll Cart System   22.3680         2

   Discount    Profit
0      0.00   41.9136
1      0.00  219.5820
2      0.00    6.8714
3      0.45 -383.0310
4      0.20    2.5164

[5 rows x 21 columns]

Product Name
Canon imageCLASS 2200 Advanced Copier                                          61599.824
Fellowes PB500 Electric Punch Plastic Comb Binding Machine with Manual Bind    27453.384
Cisco TelePresence System EX90 Videoconferencing Unit                          22638.480
Name: Sales, dtype: float64

In [ ]:
import pandas as pd
import numpy as np
df=pd.read_csv('StudentsPerformance.csv')
df.shape
df.dtypes
# they mentioned marks only we can also sum all the marks first and find the avg but the simple it can be the simple avg of the math score
# student has no name so adding the name
# random data

df['name']=np.random.choice(['ali','usman','ayesha','fatima','nasir','usba'],size=len(df))
df.info()
df.groupby('name')['math score'].mean().sort_values(ascending=True)

highest_math=df['math score'].max()
highest_reading=df['reading score'].max()
highest_writting=df['writing score'].max()
highest_writting
# finding students who failed but in math
df_failed=df[df['math score']<40]
print(len(df_failed)) #40 students failed

# subject wise avg summary does not make sense here because we have different marks but can make the summary by gen
df.groupby('gender')['math score'].mean() # male got more with 68. some thing
df.groupby('gender')['reading score'].mean()  #female got more with 72. some thing
df.groupby('gender')['writing score'].mean()

# identiffing top 5 students by all marks
df['Total_score']=df['math score']+df['reading score']+df['writing score']
df.groupby('name')['Total_score'].sum().sort_values(ascending=False).head() #got all except usman

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 9 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   gender                       1000 non-null   object
 1   race/ethnicity               1000 non-null   object
 2   parental level of education  1000 non-null   object
 3   lunch                        1000 non-null   object
 4   test preparation course      1000 non-null   object
 5   math score                   1000 non-null   int64
 6   reading score                1000 non-null   int64
 7   writing score                1000 non-null   int64
 8   name                         1000 non-null   object
dtypes: int64(3), object(6)
memory usage: 70.4+ KB
40

name
ayesha    38356
nasir     35200
fatima    34315
ali       33085
usba      33003
Name: Total_score, dtype: int64

In [ ]:
import pandas as pd
import numpy as np
df=pd.read_csv('data.csv',encoding='latin1')

df.shape #(462115, 8) long data format

df.info()
df.head()
df['Total_Sales']=df['Quantity']*df['UnitPrice']
# total spending per cus
df.groupby('CustomerID')['Total_Sales'].sum().sort_values(ascending=False)

# for the second question i dnt have category column so using the stock code something same
df.groupby('StockCode')['Quantity'].sum().sort_values(ascending=False)

#3 Identify top 5 customers by spending:little same like the first one
df.groupby('CustomerID')['Total_Sales'].sum().sort_values(ascending=False).head()

# 4 still not have category so using description
df.groupby('Description')['InvoiceNo'].nunique().sort_values(ascending=False).head()
# got 20 orders of PINK REGENCY TEACUP AND SAUCER	"555524"	20
#5 avg amount
avg=df['Total_Sales'].mean()
print(avg) # got 17

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    541909 non-null  object
 1   StockCode    541909 non-null  object
 2   Description  540455 non-null  object
 3   Quantity     541909 non-null  int64
 4   InvoiceDate  541909 non-null  object
 5   UnitPrice    541909 non-null  float64
 6   CustomerID   406829 non-null  float64
 7   Country      541909 non-null  object
dtypes: float64(2), int64(1), object(5)
memory usage: 33.1+ MB
17.98779487699964

In [ ]:
import pandas as pd
import numpy as np
df=pd.read_csv('Sample - Superstore.csv',encoding='latin1')
df.shape
df.head()
group=df.groupby(['Region','Product Name'])

group['Quantity'].sum().sort_values(ascending=False)

group['Sales'].mean().head()
# Identify highest selling product in each region
df.groupby('Region')['Product Name'].nunique()


# Compare region-wise performance
df.groupby('Region')['Sales'].sum().sort_values(ascending=False) # west has best sales

# answer of question 3
abc=group['Sales'].sum().sort_values(ascending=False)
highest=abc.groupby(level=0).idxmax()
highest

Region
Central     (Central, Canon imageCLASS 2200 Advanced Copier)
East           (East, Canon imageCLASS 2200 Advanced Copier)
South      (South, Cisco TelePresence System EX90 Videoco...
West           (West, Canon imageCLASS 2200 Advanced Copier)
Name: Sales, dtype: object

In [ ]:
import pandas as pd
import numpy as np
df=pd.read_csv('employee_records.csv')
df.shape # long format data(30,000,8)

df.info()
df['Joining_Date']=pd.to_datetime(df['Joining_Date'],format='mixed')
# 1
df.groupby('Department')['Salary'].mean().sort_values(ascending=False)

# 2
df.groupby('Department')['Salary'].max().sort_values(ascending=False)

# 3
df.groupby('Department')['Employee_ID'].nunique()

# 4
mean=df['Salary'].mean()
emp_above_avg=df[df['Salary']>mean]
print(len(emp_above_avg)) #total 14940 employees

# 5
df['Salary'].sum() #2694784278.3

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Employee_ID    30000 non-null  int64
 1   Employee_Name  30000 non-null  object
 2   Age            30000 non-null  int64
 3   Country        30000 non-null  object
 4   Department     30000 non-null  object
 5   Position       30000 non-null  object
 6   Salary         30000 non-null  float64
 7   Joining_Date   30000 non-null  object
dtypes: float64(1), int64(2), object(5)
memory usage: 1.8+ MB
14940

np.float64(2694784278.3)

In [ ]:
import pandas as pd
import numpy as np
df = pd.read_csv("hf://datasets/An-j96/SuperstoreData/data.csv")
df.shape #9994 good num of rows as well as 21 columns

df['Ship Date']=pd.to_datetime(df['Ship Date'],format='mixed')
null_num=df.isnull().sum()
null_num
df.info()
# calculating perventage
percentage=(null_num/len(df))*100
col=percentage[percentage>=50]
df=df.drop(columns=col)

# removing duplicates
print('=============')
count=df.duplicated().sum()
print('=============')
count
df=df.drop_duplicates()
# creating 3 aggregations
# which countrty has most
df['Country'].mode() # USA got the most
# most repeted or comming cus name or can also take the id

df['Customer ID'].mode() #WB-21850
# avg sales
df['Sales'].mean() #230 is avg sales

# multi level grouping
abc=df.groupby(['Country','Customer ID'])['Sales'].sum()
highest = abc.groupby(level=0).idxmax()
highest

# top and lower performer by the sales

top_performer=df.groupby('Customer ID')['Sales'].sum().sort_values(ascending=False).head(1)
bottom_performer=df.groupby('Customer ID')['Sales'].sum().sort_values(ascending=False).tail(1)

# summary
# actually i dot know how to make summary of these thing of any data set and what things must me mention in any thing so iam just using the .describe to tell the basic summary
df.describe()
# but may be i can tell the best sales by region it can also be a summary or the best customer or lowest customer
# in the summary i can write different interpretation

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9994 non-null   int64
 1   Order ID       9994 non-null   object
 2   Order Date     9994 non-null   object
 3   Ship Date      9994 non-null   datetime64[ns]
 4   Ship Mode      9994 non-null   object
 5   Customer ID    9994 non-null   object
 6   Customer Name  9994 non-null   object
 7   Segment        9994 non-null   object
 8   Country        9994 non-null   object
 9   City           9994 non-null   object
 10  State          9994 non-null   object
 11  Postal Code    9994 non-null   int64
 12  Region         9994 non-null   object
 13  Product ID     9994 non-null   object
 14  Category       9994 non-null   object
 15  Sub-Category   9994 non-null   object
 16  Product Name   9994 non-null   object
 17  Sales          9994 non-null   float64
 18  Quantity       9994 non-null   int64
 19  Discount       9994 non-null   float64
 20  Profit         9994 non-null   float64
dtypes: datetime64[ns](1), float64(3), int64(3), object(14)
memory usage: 1.6+ MB
=============
=============

,Row ID,Ship Date,Postal Code,Sales,Quantity,Discount,Profit
count,9994.000000,9994,9994.000000,9994.000000,9994.000000,9994.000000,9994.000000
mean,4997.500000,2016-05-03 23:06:58.571142912,55190.379428,229.858001,3.789574,0.156203,28.656896
min,1.000000,2014-01-07 00:00:00,1040.000000,0.444000,1.000000,0.000000,-6599.978000
25%,2499.250000,2015-05-27 00:00:00,23223.000000,17.280000,2.000000,0.000000,1.728750
50%,4997.500000,2016-06-29 00:00:00,56430.500000,54.490000,3.000000,0.200000,8.666500
75%,7495.750000,2017-05-18 00:00:00,90008.000000,209.940000,5.000000,0.200000,29.364000
max,9994.000000,2018-01-05 00:00:00,99301.000000,22638.480000,14.000000,0.800000,8399.976000
std,2885.163629,NaN,32063.693350,623.245101,2.225110,0.206452,234.260108

In [31]:
import pandas as pd
import numpy as np
# 1
df=pd.read_excel('Train.xlsx')
# 2
df.shape # a long format data
df.info()
df.head()
df['Suspicious'].unique()

df.isnull().sum() # vry column has 0 null so no need to drop nulls
print('===============')
df.duplicated().sum() # no duplicates

# data is cleaned
#3
df.groupby('ProductID').agg(
    Total_Quantity=('Quantity','sum'),
    Total_Revenue=('TotalSalesValue','sum'),
    Average_Sales=('TotalSalesValue','mean')
).sort_values(by='Total_Revenue',ascending=False)


# 4
df['PricePerunit']=df['TotalSalesValue']/df['Quantity']
df['PricePerunit']

#5
# i dont have time ore date column so i am unable to find the trend

# 6
# creating the dummy data for merging
# creating the region column
df['Region']=np.random.choice(['East','West','Nort','South'],size=len(df))
df['Category']=np.random.choice(['Office Products','Home Appliances','Wooden','Metal Products'],size=len(df))
# dont know how and where use the merge you have to tell me its proper use and code

# 7
# performance by category and region on sales
let=df.groupby(['Region','Category'])['TotalSalesValue'].sum()
highest=let.groupby(level=0).idxmax()

highest # telling the further that east has home appliances and nort got the best sales of the meta products and again south has the best metal sales and west has also best home appliances

# trying some thing new
second=let.groupby(level=1).idxmax()
# showing the Category column well but in the total sales telling the same sategory name

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 42582 entries, 0 to 42581
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ReportID         42582 non-null  object
 1   SalesPersonID    42582 non-null  object
 2   ProductID        42582 non-null  object
 3   Quantity         42582 non-null  int64
 4   TotalSalesValue  42582 non-null  int64
 5   Suspicious       42582 non-null  object
dtypes: int64(2), object(4)
memory usage: 1.9+ MB
===============

Region  Category
East    Home Appliances    43550177
        Metal Products     53536359
        Office Products    44554908
        Wooden             41572637
Nort    Home Appliances    43556060
        Metal Products     36388076
        Office Products    37423247
        Wooden             40230971
South   Home Appliances    38444258
        Metal Products     41154678
        Office Products    42392788
        Wooden             42316896
West    Home Appliances    41433944
        Metal Products     48761518
        Office Products    43316495
        Wooden             51588415
Name: TotalSalesValue, dtype: int64

In [77]:
import pandas as pd
import numpy as np
df=pd.read_csv('/content/social_media_usage.csv')
# 14
df.shape
df.info() #all the data is non-null thats great

# 15 here iam suppoesed to make an weekly hour columns but in minutes column i have only one so applying the good loggin and multiplying that daily minutes with 7 and divide by 60
df.head()
df['Weekly_hour']=(df['Daily_Minutes_Spent']*7)/60
df['Weekly_hour']

# 16
# because i dont have gender column so if want to make it real step just adding gender my self
df['gender']=np.random.choice(['male','female'],size=len(df))
df['gender']
df.info()
# now solving this 16th task but so confused about this avg total and per platform


df.groupby('gender')['Weekly_hour'].sum()
df.groupby('gender')['Weekly_hour'].mean()

df.groupby(['gender','App'])['Weekly_hour'].mean()

# so in the step 17 no columns or rows are mentioned to perfrom operation so i am makinmg my logic to apply the pivot
# ok so jut taking the logical concepts you told or taught me because i am watvhing every column cant be use in the pivot table we have to select the logical that fits only

pd.pivot_table(df,
               index='User_ID',
               columns='App',
               values='Weekly_hour',
               aggfunc='mean'

               )

df.groupby('App')['Weekly_hour'].mean()
# 18 does not have the age so can add the age to make it look like real
df['age']=np.random.choice([10,15,18,22,35],size=len(df))
df['age']
df.groupby(['App','age'])['Weekly_hour'].mean().sort_values(ascending=False)

# 19
pd.pivot_table(
               df,
               index=['gender','age'],
               columns='App',
               values='Weekly_hour',
               aggfunc='mean'

               )

# task 20th

# now the next is the last 20th and tht want interpretation and the summary reports
# df.groupby('gender')['Weekly_hour'].sum().sort_values(ascending=False) #females are using more social media then males

# df.groupby('App')['Weekly_hour'].mean().sort_values(ascending=False)#people are using insta twitter snapchat more then the any app these are the top 3


# df.groupby(['gender','age'])['Weekly_hour'].mean().sort_values(ascending=False) #10 years old males are taking more avg 32. weekly hours means little generation are using mobile phones more then the parent's

# let=df.groupby(['gender','App'])['Daily_Minutes_Spent'].sum()
# let.sort_values(ascending=False)
# # # can use it in the other way to find some thing interesting

# # papular=let.groupby(level=0).idxmax()
# # papular
# # # ok that's the thing according to the papular females are interested in the snapchat and males are interested in the facebook
# papular=let.groupby(level=1).idxmax()
# papular
let = df.groupby(['gender','App'])['Daily_Minutes_Spent'].sum()

print(let)

papular = let.groupby(level=0).idxmax()

print(papular)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 6 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   User_ID              1000 non-null   object
 1   App                  1000 non-null   object
 2   Daily_Minutes_Spent  1000 non-null   int64
 3   Posts_Per_Day        1000 non-null   int64
 4   Likes_Per_Day        1000 non-null   int64
 5   Follows_Per_Day      1000 non-null   int64
dtypes: int64(4), object(2)
memory usage: 47.0+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   User_ID              1000 non-null   object
 1   App                  1000 non-null   object
 2   Daily_Minutes_Spent  1000 non-null   int64
 3   Posts_Per_Day        1000 non-null   int64
 4   Likes_Per_Day        1000 non-null   int64
 5   Follows_Per_Day      1000 non-null   int64
 6   Weekly_hour          1000 non-null   float64
 7   gender               1000 non-null   object
dtypes: float64(1), int64(4), object(3)
memory usage: 62.6+ KB
gender  App
female  Facebook     16364
        Instagram    18734
        LinkedIn     19040
        Pinterest    17188
        Snapchat     20089
        TikTok       14627
        Twitter      17299
male    Facebook     17251
        Instagram    18240
        LinkedIn     15660
        Pinterest    15881
        Snapchat     19933
        TikTok       18285
        Twitter      18777
Name: Daily_Minutes_Spent, dtype: int64
gender
female    (female, Snapchat)
male        (male, Snapchat)
Name: Daily_Minutes_Spent, dtype: object