<a href="https://colab.research.google.com/github/muhammad-usman-tech/data-analysis-tasks/blob/main/lab_15_revise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Task 1
import pandas as pd
df=pd.read_csv('Sample - Superstore.csv',encoding='latin1')
df.shape #also of data
df.info()
df.head(7)
df['Price per Product']=df['Sales']/df['Quantity']
df['Price per Product']

data=df.groupby(['Region','Category']).agg(
    Total_Sales=('Sales',"sum"),
    Avg_Discount=('Discount','mean'),
    Profit_Margin=('Profit','sum')
)
data['Avg_Discount']=data['Avg_Discount']*100
data.sort_values(by='Profit_Margin',ascending=False)

FileNotFoundError: [Errno 2] No such file or directory: 'Sample - Superstore.csv'

In [ ]:
# Task 4
import pandas as pd
df=pd.read_csv('/content/country_vaccinations.csv',encoding='latin1')
df.shape #it has 86 thousand rows
df.info()
df.head()

data=df.groupby('country').agg(
    Total_vacni=('total_vaccinations','sum')
)

data.sort_values(by='Total_vacni',ascending=False).head(10) #it will show the total_vac by country and also the top 10 country by vac ratio

# now generating the rolling avg step
df['date']=pd.to_datetime(df['date'],format='mixed')
df['days_name']=df['date'].dt.day_name()
df['days_name']
df.groupby('days_name')['total_vaccinations'].rolling(3).mean().sort_values(ascending=False)
# i dont know what does this 3.233806e+09 means which is saying on the tuesday and it is interprecepting like this. i dont know if this
# all is logically ok or not
df['date']=pd.to_datetime(df['date'],format='mixed')
df.groupby(['country','date'])['daily_vaccinations'].rolling(7).mean()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 86512 entries, 0 to 86511
Data columns (total 15 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   country                              86512 non-null  object
 1   iso_code                             86512 non-null  object
 2   date                                 86512 non-null  object
 3   total_vaccinations                   43607 non-null  float64
 4   people_vaccinated                    41294 non-null  float64
 5   people_fully_vaccinated              38802 non-null  float64
 6   daily_vaccinations_raw               35362 non-null  float64
 7   daily_vaccinations                   86213 non-null  float64
 8   total_vaccinations_per_hundred       43607 non-null  float64
 9   people_vaccinated_per_hundred        41294 non-null  float64
 10  people_fully_vaccinated_per_hundred  38802 non-null  float64
 11  daily_vaccinations_per_million       86213 non-null  float64
 12  vaccines                             86512 non-null  object
 13  source_name                          86512 non-null  object
 14  source_website                       86512 non-null  object
dtypes: float64(9), object(6)
memory usage: 9.9+ MB

country      date
Afghanistan  2021-02-22  0       NaN
             2021-02-23  1       NaN
             2021-02-24  2       NaN
             2021-02-25  3       NaN
             2021-02-26  4       NaN
                                  ..
Zimbabwe     2022-03-25  86507   NaN
             2022-03-26  86508   NaN
             2022-03-27  86509   NaN
             2022-03-28  86510   NaN
             2022-03-29  86511   NaN
Name: daily_vaccinations, Length: 86512, dtype: float64

In [ ]:
import pandas as pd
df=pd.read_csv('/content/olist_order_items_dataset.csv')
# df.info()
df2=pd.read_csv('/content/olist_orders_dataset.csv')
df=df.merge(df2,on='order_id',how='inner')

df3=pd.read_csv('olist_customers_dataset.csv')
# df3.info()
# df.info()
df=df.merge(df3,on='customer_id',how='inner')

df4=pd.read_csv('olist_products_dataset.csv')
# df4.info()

df=df.merge(df4,on='product_id',how='inner')
df.info()
df.shape #(112650, 26)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 112650 entries, 0 to 112649
Data columns (total 26 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   order_id                       112650 non-null  object
 1   order_item_id                  112650 non-null  int64
 2   product_id                     112650 non-null  object
 3   seller_id                      112650 non-null  object
 4   shipping_limit_date            112650 non-null  object
 5   price                          112650 non-null  float64
 6   freight_value                  112650 non-null  float64
 7   customer_id                    112650 non-null  object
 8   order_status                   112650 non-null  object
 9   order_purchase_timestamp       112650 non-null  object
 10  order_approved_at              112635 non-null  object
 11  order_delivered_carrier_date   111456 non-null  object
 12  order_delivered_customer_date  110196 non-null  object
 13  order_estimated_delivery_date  112650 non-null  object
 14  customer_unique_id             112650 non-null  object
 15  customer_zip_code_prefix       112650 non-null  int64
 16  customer_city                  112650 non-null  object
 17  customer_state                 112650 non-null  object
 18  product_category_name          111047 non-null  object
 19  product_name_lenght            111047 non-null  float64
 20  product_description_lenght     111047 non-null  float64
 21  product_photos_qty             111047 non-null  float64
 22  product_weight_g               112632 non-null  float64
 23  product_length_cm              112632 non-null  float64
 24  product_height_cm              112632 non-null  float64
 25  product_width_cm               112632 non-null  float64
dtypes: float64(9), int64(2), object(15)
memory usage: 22.3+ MB

(112650, 26)

In [ ]:
import pandas as pd
import numpy as np

df2=pd.read_csv('/content/flights.csv')
df2.shape
df2.info()
df2['DEPARTURE_DELAY'] #some values of the departure delay are in -ve it can mean it was early like -6 can mean it was 6 min early and i don't know if this time is in minutes or not so just adding all that time

# taking dataframe2
df2['day_name']=df2['DAY_OF_WEEK'].replace({1:'Monday',2:'Tuesdy',3:'wed',4:'thurs',5:'fri',6:'sat',7:'sunday'})
# df2.groupby(['DAY_OF_WEEK','AIRLINE'])['DEPARTURE_DELAY'].sum().sort_values(ascending=False)
df2.pivot_table(index='day_name',columns='AIRLINE',values='DEPARTURE_DELAY',aggfunc='mean')

/tmp/ipykernel_811/1474331147.py:4: DtypeWarning: Columns (7,8) have mixed types. Specify dtype option on import or set low_memory=False.
  df2=pd.read_csv('/content/flights.csv')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5819079 entries, 0 to 5819078
Data columns (total 31 columns):
 #   Column               Dtype
---  ------               -----
 0   YEAR                 int64
 1   MONTH                int64
 2   DAY                  int64
 3   DAY_OF_WEEK          int64
 4   AIRLINE              object
 5   FLIGHT_NUMBER        int64
 6   TAIL_NUMBER          object
 7   ORIGIN_AIRPORT       object
 8   DESTINATION_AIRPORT  object
 9   SCHEDULED_DEPARTURE  int64
 10  DEPARTURE_TIME       float64
 11  DEPARTURE_DELAY      float64
 12  TAXI_OUT             float64
 13  WHEELS_OFF           float64
 14  SCHEDULED_TIME       float64
 15  ELAPSED_TIME         float64
 16  AIR_TIME             float64
 17  DISTANCE             int64
 18  WHEELS_ON            float64
 19  TAXI_IN              float64
 20  SCHEDULED_ARRIVAL    int64
 21  ARRIVAL_TIME         float64
 22  ARRIVAL_DELAY        float64
 23  DIVERTED             int64
 24  CANCELLED            int64
 25  CANCELLATION_REASON  object
 26  AIR_SYSTEM_DELAY     float64
 27  SECURITY_DELAY       float64
 28  AIRLINE_DELAY        float64
 29  LATE_AIRCRAFT_DELAY  float64
 30  WEATHER_DELAY        float64
dtypes: float64(16), int64(10), object(5)
memory usage: 1.3+ GB

AIRLINE,AA,AS,B6,DL,EV,F9,HA,MQ,NK,OO,UA,US,VX,WN
day_name,,,,,,,,,,,,,,
Monday,10.511397,2.439938,13.320299,8.406116,11.131696,16.031717,0.627950,13.594260,18.795627,9.662757,16.235989,7.060184,10.906626,11.199066
Tuesdy,6.750830,0.775753,12.744261,7.662513,8.986562,13.305788,-1.554867,9.003150,15.714659,7.850453,15.221942,6.475249,7.467289,10.441113
fri,9.604086,2.695551,10.562236,7.271534,7.682151,12.633725,2.755693,10.887275,15.786105,7.530409,13.672102,6.517668,10.784495,11.120366
sat,8.619112,1.189560,9.077030,5.443125,6.047855,13.327767,0.250237,7.121726,15.780295,5.937152,12.563504,5.355319,4.510900,9.426430
sunday,9.615946,2.418364,12.119106,6.594029,8.293996,13.560065,0.138239,10.614979,17.149202,8.103094,13.667667,7.487922,13.576068,10.423010
thurs,9.411084,2.173562,12.892693,8.712564,9.336234,11.375486,1.150585,10.086080,14.722126,7.611775,14.887428,6.120980,10.219335,11.448429
wed,7.738107,0.709696,9.699166,6.981081,8.849306,13.261490,-0.221614,9.069924,13.668351,7.605124,14.282201,3.858715,4.784685,9.789381

In [ ]:
import pandas as pd
import numpy as np
df=pd.read_csv('/content/sales data-set.csv')
df.shape
df.info()
df['IsHoliday']


df.groupby(['Store','Dept']).agg(
    Total_sales=('Weekly_Sales','sum'),
    Holiday_Sales=('Weekly_Sales',lambda x: x[df.loc[x.index,'IsHoliday']].sum())

)

# monthly sales

df['Date']=pd.to_datetime(df['Date'],format='mixed')
df['Month']=df['Date'].dt.month
df['Month']

data=df.groupby('Month')['Weekly_Sales'].sum()

data2=data.pct_change()*100
data2

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 421570 entries, 0 to 421569
Data columns (total 5 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   Store         421570 non-null  int64
 1   Dept          421570 non-null  int64
 2   Date          421570 non-null  object
 3   Weekly_Sales  421570 non-null  float64
 4   IsHoliday     421570 non-null  bool
dtypes: bool(1), float64(1), int64(2), object(1)
memory usage: 13.3+ MB

Month
1           NaN
2     22.418745
3      6.026663
4     16.592545
5     -6.140683
6     -5.065016
7      3.181809
8     -4.901661
9      4.661306
10     2.097531
11   -23.842267
12    30.469534
Name: Weekly_Sales, dtype: float64

In [ ]:
import pandas as pd
import numpy as np
df=pd.read_csv('/content/tmdb_5000_movies.csv')
df.shape

df2=pd.read_csv('/content/tmdb_5000_credits.csv')
df2.shape

merged=pd.merge(df,df2,left_on='id',right_on='movie_id',how='inner')
df.info()
df2.info()
merged.shape

df['genres']

import ast

merged['genres'] = merged['genres'].apply(ast.literal_eval)
merged['genres'] = merged['genres'].apply(
    lambda x: [item['name'] for item in x]
)

merged = merged.explode('genres')

merged['genres']

merged['ROI']=(df['revenue']-df['budget'])/df['budget']
data=df.groupby('genres')['revenue'].sum()
data
merged['date']=pd.to

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4803 entries, 0 to 4802
Data columns (total 20 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   budget                4803 non-null   int64
 1   genres                4803 non-null   object
 2   homepage              1712 non-null   object
 3   id                    4803 non-null   int64
 4   keywords              4803 non-null   object
 5   original_language     4803 non-null   object
 6   original_title        4803 non-null   object
 7   overview              4800 non-null   object
 8   popularity            4803 non-null   float64
 9   production_companies  4803 non-null   object
 10  production_countries  4803 non-null   object
 11  release_date          4802 non-null   object
 12  revenue               4803 non-null   int64
 13  runtime               4801 non-null   float64
 14  spoken_languages      4803 non-null   object
 15  status                4803 non-null   object
 16  tagline               3959 non-null   object
 17  title                 4803 non-null   object
 18  vote_average          4803 non-null   float64
 19  vote_count            4803 non-null   int64
dtypes: float64(3), int64(4), object(13)
memory usage: 750.6+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4803 entries, 0 to 4802
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   movie_id  4803 non-null   int64
 1   title     4803 non-null   object
 2   cast      4803 non-null   object
 3   crew      4803 non-null   object
dtypes: int64(1), object(3)
memory usage: 150.2+ KB

In [4]:
import pandas as pd
import numpy as np
df=pd.read_csv('/content/melt_rolling_practice_sales.csv')
df.shape

df.info()
df_long=pd.melt(
    id_vars='Month',
    var_name='Store',
    value_name='Sales',
    frame=df
)
df_long

df_long=df_long.sort_values(by='Store',ascending=True)

df_long
month_order = [
    'Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun',
    'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'
]

df_long['Month']=pd.Categorical(
    df_long['Month'],
    categories=month_order,
    ordered=True
)

df_long=df_long.sort_values(by=['Month','Store'],ascending=True)
df_long['rolling avg']=(df_long.groupby('Store')['Sales']
                        .rolling(3)
                        .mean().reset_index(level=0,drop=True))
df_long

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Month    12 non-null     object
 1   Store_A  12 non-null     int64
 2   Store_B  12 non-null     int64
 3   Store_C  12 non-null     int64
dtypes: int64(3), object(1)
memory usage: 516.0+ bytes

   Month    Store  Sales   rolling avg
0    Jan  Store_A  12000           NaN
12   Jan  Store_B  15000           NaN
24   Jan  Store_C  11000           NaN
1    Feb  Store_A  13500           NaN
13   Feb  Store_B  14800           NaN
25   Feb  Store_C  12500           NaN
2    Mar  Store_A  14200  13233.333333
14   Mar  Store_B  16000  15266.666667
26   Mar  Store_C  13000  12166.666667
3    Apr  Store_A  15000  14233.333333
15   Apr  Store_B  15500  15433.333333
27   Apr  Store_C  13800  13100.000000
4    May  Store_A  16200  15133.333333
16   May  Store_B  17000  16166.666667
28   May  Store_C  14500  13766.666667
5    Jun  Store_A  15800  15666.666667
17   Jun  Store_B  17500  16666.666667
29   Jun  Store_C  15200  14500.000000
6    Jul  Store_A  17000  16333.333333
18   Jul  Store_B  18000  17500.000000
30   Jul  Store_C  16000  15233.333333
7    Aug  Store_A  17600  16800.000000
19   Aug  Store_B  18500  18000.000000
31   Aug  Store_C  16500  15900.000000
8    Sep  Store_A  16800  17133.333333
20   Sep  Store_B  17800  18100.000000
32   Sep  Store_C  15800  16100.000000
9    Oct  Store_A  18200  17533.333333
21   Oct  Store_B  19000  18433.333333
33   Oct  Store_C  17200  16500.000000
10   Nov  Store_A  19500  18166.666667
22   Nov  Store_B  20500  19100.000000
34   Nov  Store_C  18500  17166.666667
11   Dec  Store_A  22000  19900.000000
23   Dec  Store_B  23000  20833.333333
35   Dec  Store_C  21000  18900.000000